import { act, fireEvent, render, screen, waitFor } from "@testing-library/react";
import { IonApp } from "@ionic/react";
import { MemoryRouter } from "react-router";
import InspectionAdd from "./InspectionAdd";
import api from "../../../services/axios/axios";

jest.mock("../../../services/axios/axios");
const mockAlerts = { showErrorAlert: jest.fn(), showSuccessAlert: jest.fn(), showWarningAlert: jest.fn() };
jest.mock("../../../services/hooks/useAlert", () => ({ useAlert: () => mockAlerts }));

const mockedApi = api as jest.Mocked<typeof api>;
const MANUAL = {
  id: 5,
  date: "2026-09-01",
  driverName: "Manual",
  odometer: 100,
  expenses: [],
  carBodyDamages: [],
};
const FROM_CHECKLIST = { ...MANUAL, id: 6, driverName: "João", originDocumentId: 9, driverCarId: 3, fuelLevel: "HALF" };

const renderInspection = (initialValues: any) => {
  const closeModal = jest.fn();
  render(
    <IonApp>
      <MemoryRouter>
        <InspectionAdd closeModal={closeModal} initialValues={initialValues} carId="20" />
      </MemoryRouter>
    </IonApp>
  );
  return closeModal;
};

/** The "Adicionar" buttons of the expenses and of the damages, and whether each is hidden. */
const addButtonsHidden = () =>
  screen.getAllByText("Adicionar").map((node) => Boolean(node.closest("ion-button")?.hasAttribute("hidden")));

describe("Inspection - registro gerado pelo checklist", () => {
  beforeAll(() => {
    (global as any).IntersectionObserver = class {
      observe() {}
      unobserve() {}
      disconnect() {}
    };
  });

  beforeEach(() => {
    jest.resetAllMocks();
    mockedApi.get.mockResolvedValue({ data: [] });
    mockedApi.put.mockResolvedValue({ data: MANUAL });
  });

  it("an inspection generated by a finalized checklist cannot be edited, get expenses or be deleted", async () => {
    renderInspection(FROM_CHECKLIST);

    expect(await screen.findByTestId("inspection-from-checklist")).toHaveTextContent(/não pode ser alterada nem excluída/);
    expect(screen.queryByText("Salvar")).not.toBeInTheDocument();
    expect(screen.queryByText("Excluir Inspeção")).not.toBeInTheDocument();
    expect(addButtonsHidden()).toEqual([true, true]);
    expect(mockedApi.put).not.toHaveBeenCalled();
    expect(mockedApi.post).not.toHaveBeenCalled();
    expect(mockedApi.delete).not.toHaveBeenCalled();
  });

  it("a manual inspection stays editable: save, add expenses and delete", async () => {
    const closeModal = renderInspection(MANUAL);

    expect(screen.queryByTestId("inspection-from-checklist")).not.toBeInTheDocument();
    expect(screen.getByText("Excluir Inspeção")).toBeInTheDocument();
    expect(addButtonsHidden()).toEqual([false, false]);

    await act(async () => {
      fireEvent.click(screen.getByText("Salvar"));
    });

    await waitFor(() => expect(mockedApi.put).toHaveBeenCalledTimes(1));
    expect(mockedApi.put.mock.calls[0][0]).toBe("/api/inspections/5");
    await waitFor(() => expect(closeModal).toHaveBeenCalledWith(MANUAL));
  });
});
