package com.localuz.service;
import static org.assertj.core.api.Assertions.*; import static org.mockito.ArgumentMatchers.any; import static org.mockito.Mockito.*;
import com.localuz.config.MercadoPagoProperties; import com.localuz.domain.*; import com.localuz.domain.enumeration.PlanCode; import com.localuz.repository.*; import com.localuz.service.dto.PricingResult;
import java.math.BigDecimal; import java.util.*; import java.util.stream.Stream; import org.junit.jupiter.api.*; import org.junit.jupiter.params.ParameterizedTest; import org.junit.jupiter.params.provider.*; import org.mockito.ArgumentCaptor;
class BillingCheckoutServiceTest {
 private final PricingService pricing=mock(PricingService.class); private final PlanRepository plans=mock(PlanRepository.class); private final BillingCheckoutRepository checkouts=mock(BillingCheckoutRepository.class); private final MercadoPagoClient client=mock(MercadoPagoClient.class); private final CarRepository cars=mock(CarRepository.class); private final UserRepository users=mock(UserRepository.class); private final MercadoPagoProperties properties=new MercadoPagoProperties(); private BillingCheckoutService service; private User user;
 @BeforeEach void setup(){reset(pricing,plans,checkouts,client,cars,users);properties.setEnabled(true);properties.setAccessToken("test-only");properties.setBackUrl("https://frotto.test/menu/meu-plano");service=new BillingCheckoutService(properties,pricing,plans,checkouts,client,cars,users);user=new User();user.setId(7L);user.setEmail("payer@example.com");when(users.findByIdForBillingCheckoutLock(7L)).thenReturn(Optional.of(user));when(checkouts.save(any())).thenAnswer(i->i.getArgument(0));}
 private Plan plan(PlanCode code,int min,Integer max){Plan p=new Plan();p.setCode(code);p.setMinVehicles(min);p.setMaxVehicles(max);p.setActive(true);when(plans.findByCode(code)).thenReturn(Optional.of(p));return p;}
 private BillingCheckout execute(int count,PlanCode selected,String price,PlanCode required,int selectedMin,int requiredMin,Integer max){Plan selectedPlan=plan(selected,selectedMin,max);Plan requiredPlan=selected==required?selectedPlan:plan(required,requiredMin,count);when(pricing.resolvePlanForVehicleCount(count)).thenReturn(requiredPlan);when(pricing.calculatePriceForPlan(selected,count)).thenReturn(new PricingResult(selected,selected.name(),count,new BigDecimal(price),List.of()));return service.createIntent(user,selected,count);}
 static Stream<Arguments> allowed(){return Stream.of(Arguments.of(2,PlanCode.BRONZE,"15.90",PlanCode.FREE,3,0,5),Arguments.of(2,PlanCode.GOLD,"79.90",PlanCode.FREE,16,0,30),Arguments.of(10,PlanCode.SILVER,"44.90",PlanCode.SILVER,6,6,15),Arguments.of(20,PlanCode.GOLD,"79.90",PlanCode.GOLD,16,16,30),Arguments.of(31,PlanCode.PLATINUM,"82.40",PlanCode.PLATINUM,31,31,100),Arguments.of(101,PlanCode.FROTTA,"256.90",PlanCode.FROTTA,101,101,null));}
 @ParameterizedTest @MethodSource("allowed") void allowsRequiredOrHigherAndSnapshotsExactQuote(int count,PlanCode selected,String price,PlanCode required,int selectedMin,int requiredMin,Integer max){BillingCheckout result=execute(count,selected,price,required,selectedMin,requiredMin,max);assertThat(result.getQuotedPrice()).isEqualByComparingTo(price);verify(pricing).calculatePriceForPlan(selected,count);}
 @Test void rejectsBronzeForTen(){assertThatThrownBy(()->execute(10,PlanCode.BRONZE,"15.90",PlanCode.SILVER,3,6,5)).isInstanceOf(IllegalArgumentException.class);verify(checkouts,never()).save(any());}
 @Test void rejectsSilverForTwenty(){assertThatThrownBy(()->execute(20,PlanCode.SILVER,"44.90",PlanCode.GOLD,6,16,15)).isInstanceOf(IllegalArgumentException.class);}
 @Test void rejectsPlatinumFor101(){assertThatThrownBy(()->execute(101,PlanCode.PLATINUM,"0",PlanCode.FROTTA,31,101,100)).isInstanceOf(IllegalArgumentException.class);}
 @Test void disabledAndMissingTokenFailBeforePricing(){properties.setEnabled(false);assertThatThrownBy(()->service.createIntent(user,PlanCode.GOLD,2)).hasMessageContaining("disabled");properties.setEnabled(true);properties.setAccessToken(" ");assertThatThrownBy(()->service.createIntent(user,PlanCode.GOLD,2)).hasMessageContaining("not configured");verifyNoInteractions(pricing,plans,checkouts);}
 @Test void requiresAuthenticatedUser(){assertThatThrownBy(()->service.createIntent(null,PlanCode.GOLD,2)).hasMessageContaining("Authenticated");}
 @Test void checkoutSuccessPersistsProviderSnapshotAndKeepsStableIdentity(){Plan free=plan(PlanCode.FREE,0,2);Plan gold=plan(PlanCode.GOLD,16,30);when(cars.countByUserIdAndActiveTrue(7L)).thenReturn(2L);when(pricing.resolvePlanForVehicleCount(2)).thenReturn(free);when(pricing.calculatePriceForPlan(PlanCode.GOLD,2)).thenReturn(new PricingResult(PlanCode.GOLD,"GOLD",2,new BigDecimal("79.90"),List.of()));when(client.createPreapproval(any(),any())).thenAnswer(i->{com.localuz.service.dto.MercadoPagoPreapprovalRequest r=i.getArgument(0);return new com.localuz.service.dto.MercadoPagoPreapproval("pre-1","pending",r.getExternalReference(),"https://mp.test/checkout");});BillingCheckout result=service.createCheckout(user,PlanCode.GOLD);assertThat(result.getPlan()).isSameAs(gold);assertThat(result.getQuotedPrice()).isEqualByComparingTo("79.90");assertThat(result.getProviderSubscriptionId()).isEqualTo("pre-1");assertThat(result.getProviderStatus()).isEqualTo("pending");assertThat(result.getInitPoint()).isEqualTo("https://mp.test/checkout");assertThat(result.getStatus()).isEqualTo(com.localuz.domain.enumeration.BillingCheckoutStatus.PROVIDER_PENDING);assertThat(result.getExternalReference()).isNotBlank();assertThat(result.getIdempotencyKey()).isNotBlank();verify(checkouts,times(2)).save(same(result));}
 @Test void ambiguousProviderFailureKeepsIdentityAndHistory(){Plan free=plan(PlanCode.FREE,0,2);plan(PlanCode.GOLD,16,30);when(cars.countByUserIdAndActiveTrue(7L)).thenReturn(2L);when(pricing.resolvePlanForVehicleCount(2)).thenReturn(free);when(pricing.calculatePriceForPlan(PlanCode.GOLD,2)).thenReturn(new PricingResult(PlanCode.GOLD,"GOLD",2,new BigDecimal("79.90"),List.of()));when(client.createPreapproval(any(),any())).thenThrow(new MercadoPagoException("timeout",true));assertThatThrownBy(()->service.createCheckout(user,PlanCode.GOLD)).isInstanceOf(MercadoPagoException.class);ArgumentCaptor<BillingCheckout> captor=ArgumentCaptor.forClass(BillingCheckout.class);verify(checkouts,times(2)).save(captor.capture());BillingCheckout persisted=captor.getAllValues().get(1);assertThat(persisted.getStatus()).isEqualTo(com.localuz.domain.enumeration.BillingCheckoutStatus.PROVIDER_UNKNOWN);assertThat(persisted.getExternalReference()).isNotBlank();assertThat(persisted.getIdempotencyKey()).isNotBlank();verify(client,times(1)).createPreapproval(any(),eq(persisted.getIdempotencyKey()));}
 @Test void conclusiveProviderFailureIsFailed(){Plan free=plan(PlanCode.FREE,0,2);plan(PlanCode.GOLD,16,30);when(cars.countByUserIdAndActiveTrue(7L)).thenReturn(2L);when(pricing.resolvePlanForVehicleCount(2)).thenReturn(free);when(pricing.calculatePriceForPlan(PlanCode.GOLD,2)).thenReturn(new PricingResult(PlanCode.GOLD,"GOLD",2,new BigDecimal("79.90"),List.of()));when(client.createPreapproval(any(),any())).thenThrow(new MercadoPagoException("400",false));assertThatThrownBy(()->service.createCheckout(user,PlanCode.GOLD)).isInstanceOf(MercadoPagoException.class);ArgumentCaptor<BillingCheckout> captor=ArgumentCaptor.forClass(BillingCheckout.class);verify(checkouts,times(2)).save(captor.capture());assertThat(captor.getValue().getStatus()).isEqualTo(com.localuz.domain.enumeration.BillingCheckoutStatus.FAILED);}
 @Test void checkoutRejectsMissingAndInvalidAuthenticatedEmailBeforeProvider(){user.setEmail(null);assertThatThrownBy(()->service.createCheckout(user,PlanCode.GOLD)).hasMessageContaining("valid email");user.setEmail("invalid");assertThatThrownBy(()->service.createCheckout(user,PlanCode.GOLD)).hasMessageContaining("valid email");verifyNoInteractions(client,cars);}
 @ParameterizedTest @EnumSource(value=com.localuz.domain.enumeration.BillingCheckoutStatus.class,names={"CREATED","PROVIDER_PENDING","PROVIDER_UNKNOWN"}) void unresolvedCheckoutBlocksBeforePricingAndProvider(com.localuz.domain.enumeration.BillingCheckoutStatus status){when(checkouts.existsByUserIdAndStatusIn(eq(7L),argThat(statuses->statuses.contains(status)))).thenReturn(true);assertThatThrownBy(()->service.createCheckout(user,PlanCode.GOLD)).isInstanceOf(com.localuz.web.rest.errors.BillingCheckoutInProgressException.class).extracting("status.statusCode").isEqualTo(409);verify(users).findByIdForBillingCheckoutLock(7L);verifyNoInteractions(client,cars,pricing,plans);verify(checkouts,never()).save(any());}
 @ParameterizedTest @EnumSource(value=com.localuz.domain.enumeration.BillingCheckoutStatus.class,names={"FAILED","CANCELED"}) void terminalCheckoutAllowsANewIdentity(com.localuz.domain.enumeration.BillingCheckoutStatus previousStatus){Plan free=plan(PlanCode.FREE,0,2);plan(PlanCode.GOLD,16,30);when(cars.countByUserIdAndActiveTrue(7L)).thenReturn(2L);when(pricing.resolvePlanForVehicleCount(2)).thenReturn(free);when(pricing.calculatePriceForPlan(PlanCode.GOLD,2)).thenReturn(new PricingResult(PlanCode.GOLD,"GOLD",2,new BigDecimal("79.90"),List.of()));when(client.createPreapproval(any(),any())).thenAnswer(i->{com.localuz.service.dto.MercadoPagoPreapprovalRequest r=i.getArgument(0);return new com.localuz.service.dto.MercadoPagoPreapproval("new-preapproval","pending",r.getExternalReference(),"https://mp.test/new");});BillingCheckout result=service.createCheckout(user,PlanCode.GOLD);assertThat(previousStatus).isIn(com.localuz.domain.enumeration.BillingCheckoutStatus.FAILED,com.localuz.domain.enumeration.BillingCheckoutStatus.CANCELED);assertThat(result.getExternalReference()).isNotBlank().isNotEqualTo("old-external-reference");assertThat(result.getIdempotencyKey()).isNotBlank().isNotEqualTo("old-idempotency-key");verify(client).createPreapproval(any(),eq(result.getIdempotencyKey()));}
 @Test void serializedSecondRequestSeesFirstIntentAndDoesNotCallProviderAgain(){Plan free=plan(PlanCode.FREE,0,2);plan(PlanCode.GOLD,16,30);when(cars.countByUserIdAndActiveTrue(7L)).thenReturn(2L);when(pricing.resolvePlanForVehicleCount(2)).thenReturn(free);when(pricing.calculatePriceForPlan(PlanCode.GOLD,2)).thenReturn(new PricingResult(PlanCode.GOLD,"GOLD",2,new BigDecimal("79.90"),List.of()));when(checkouts.existsByUserIdAndStatusIn(eq(7L),anyList())).thenReturn(false,true);when(client.createPreapproval(any(),any())).thenAnswer(i->{com.localuz.service.dto.MercadoPagoPreapprovalRequest r=i.getArgument(0);return new com.localuz.service.dto.MercadoPagoPreapproval("pre-1","pending",r.getExternalReference(),"https://mp.test/checkout");});service.createCheckout(user,PlanCode.GOLD);assertThatThrownBy(()->service.createCheckout(user,PlanCode.GOLD)).isInstanceOf(com.localuz.web.rest.errors.BillingCheckoutInProgressException.class);verify(users,times(2)).findByIdForBillingCheckoutLock(7L);verify(client,times(1)).createPreapproval(any(),any());}
 @Test void repositoryLockAndTransactionSerializeTheCheckThenCreateSection() throws Exception {org.springframework.data.jpa.repository.Lock lock=UserRepository.class.getMethod("findByIdForBillingCheckoutLock",Long.class).getAnnotation(org.springframework.data.jpa.repository.Lock.class);assertThat(lock).isNotNull();assertThat(lock.value()).isEqualTo(javax.persistence.LockModeType.PESSIMISTIC_WRITE);assertThat(BillingCheckoutService.class.getMethod("createCheckout",User.class,PlanCode.class).getAnnotation(org.springframework.transaction.annotation.Transactional.class)).isNotNull();}
 @Test void serviceHasNoSubscriptionDependency(){assertThat(Arrays.stream(BillingCheckoutService.class.getDeclaredFields()).map(java.lang.reflect.Field::getType).map(Class::getSimpleName)).noneMatch(name->name.contains("Subscription"));}

 private void stubGoldCheckoutPricing(){Plan free=plan(PlanCode.FREE,0,2);plan(PlanCode.GOLD,16,30);when(cars.countByUserIdAndActiveTrue(7L)).thenReturn(2L);when(pricing.resolvePlanForVehicleCount(2)).thenReturn(free);when(pricing.calculatePriceForPlan(PlanCode.GOLD,2)).thenReturn(new PricingResult(PlanCode.GOLD,"GOLD",2,new BigDecimal("79.90"),List.of()));}
 private ArgumentCaptor<com.localuz.service.dto.MercadoPagoPreapprovalRequest> stubProviderSuccessAndCaptureRequest(){ArgumentCaptor<com.localuz.service.dto.MercadoPagoPreapprovalRequest> captor=ArgumentCaptor.forClass(com.localuz.service.dto.MercadoPagoPreapprovalRequest.class);when(client.createPreapproval(captor.capture(),any())).thenAnswer(i->{com.localuz.service.dto.MercadoPagoPreapprovalRequest r=i.getArgument(0);return new com.localuz.service.dto.MercadoPagoPreapproval("pre-1","pending",r.getExternalReference(),"https://mp.test/checkout");});return captor;}

 @Test void testModeDisabledIgnoresConfiguredTestPayerEmailAndUsesFrottoUserEmail(){
  properties.setTestMode(false); properties.setTestPayerEmail("buyer-test@testuser.com");
  stubGoldCheckoutPricing(); var captor=stubProviderSuccessAndCaptureRequest();
  BillingCheckout result=service.createCheckout(user,PlanCode.GOLD);
  assertThat(captor.getValue().getPayerEmail()).isEqualTo("payer@example.com");
  assertThat(captor.getValue().getExternalReference()).isEqualTo(result.getExternalReference());
  assertThat(captor.getValue().getReason()).isEqualTo("Frotto - plano GOLD");
  assertThat(captor.getValue().getTransactionAmount()).isEqualByComparingTo("79.90");
  assertThat(captor.getValue().getCurrencyId()).isEqualTo("BRL");
  assertThat(captor.getValue().getBackUrl()).isEqualTo("https://frotto.test/menu/meu-plano");
 }

 @Test void testModeEnabledWithConfiguredEmailUsesTestPayerEmailAndLeavesRestOfPayloadUnchanged(){
  properties.setTestMode(true); properties.setTestPayerEmail("buyer-test@testuser.com");
  stubGoldCheckoutPricing(); var captor=stubProviderSuccessAndCaptureRequest();
  BillingCheckout result=service.createCheckout(user,PlanCode.GOLD);
  assertThat(captor.getValue().getPayerEmail()).isEqualTo("buyer-test@testuser.com");
  assertThat(captor.getValue().getExternalReference()).isEqualTo(result.getExternalReference());
  assertThat(captor.getValue().getReason()).isEqualTo("Frotto - plano GOLD");
  assertThat(captor.getValue().getTransactionAmount()).isEqualByComparingTo("79.90");
  assertThat(captor.getValue().getCurrencyId()).isEqualTo("BRL");
  assertThat(captor.getValue().getBackUrl()).isEqualTo("https://frotto.test/menu/meu-plano");
 }

 @Test void testModeEnabledWithoutConfiguredEmailFailsBeforeCallingProvider(){
  properties.setTestMode(true); properties.setTestPayerEmail("   ");
  stubGoldCheckoutPricing();
  assertThatThrownBy(()->service.createCheckout(user,PlanCode.GOLD)).isInstanceOf(IllegalStateException.class).hasMessageContaining("test payer email");
  verifyNoInteractions(client);
 }

 @Test void missingTestOverrideConfigurationKeepsCurrentBehavior(){
  assertThat(properties.isTestMode()).isFalse(); assertThat(properties.hasTestPayerEmail()).isFalse();
  stubGoldCheckoutPricing(); var captor=stubProviderSuccessAndCaptureRequest();
  service.createCheckout(user,PlanCode.GOLD);
  assertThat(captor.getValue().getPayerEmail()).isEqualTo("payer@example.com");
 }
}
