package com.localuz.service;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.Mockito.*;
import com.localuz.domain.*;
import com.localuz.domain.enumeration.*;
import com.localuz.repository.*;
import com.localuz.service.dto.*;
import java.math.BigDecimal;
import java.time.Instant;
import java.util.Optional;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.ArgumentCaptor;

class MercadoPagoWebhookProcessorTest {
    private MercadoPagoClient client;private BillingCheckoutRepository checkouts;private SubscriptionRepository subscriptions;private MercadoPagoWebhookEventRepository events;private MercadoPagoWebhookProcessor processor;private BillingCheckout checkout;
    @BeforeEach void setUp(){client=mock(MercadoPagoClient.class);checkouts=mock(BillingCheckoutRepository.class);subscriptions=mock(SubscriptionRepository.class);events=mock(MercadoPagoWebhookEventRepository.class);processor=new MercadoPagoWebhookProcessor(client,checkouts,subscriptions,events);checkout=checkout();when(checkouts.findByProviderSubscriptionId("pre-1")).thenReturn(Optional.empty());when(checkouts.findByExternalReference("ref-1")).thenReturn(Optional.of(checkout));when(subscriptions.findByExternalProviderAndExternalSubscriptionId("MERCADO_PAGO","pre-1")).thenReturn(Optional.empty());}
    @Test void authorizedCreatesOnePaymentProviderFromCheckoutSnapshot(){when(client.getPreapproval("pre-1")).thenReturn(preapproval("authorized"));processor.process("req-1","subscription_preapproval","pre-1");ArgumentCaptor<Subscription> captor=ArgumentCaptor.forClass(Subscription.class);verify(subscriptions).save(captor.capture());Subscription saved=captor.getValue();assertThat(saved.getStatus()).isEqualTo(SubscriptionStatus.ACTIVE);assertThat(saved.getSource()).isEqualTo(SubscriptionSource.PAYMENT_PROVIDER);assertThat(saved.getContractedPrice()).isEqualByComparingTo("79.90");assertThat(saved.getContractedVehicleCount()).isEqualTo(12);assertThat(checkout.getStatus()).isEqualTo(BillingCheckoutStatus.AUTHORIZED);}
    @Test void duplicateDoesNotCallProvider(){when(events.existsByRequestIdAndEventTypeAndResourceId("req","subscription_preapproval","pre-1")).thenReturn(true);assertThat(processor.process("req","subscription_preapproval","pre-1")).isEqualTo(MercadoPagoWebhookProcessor.Result.DUPLICATE);verifyNoInteractions(client);}
    @Test void differentRequestIdsUpdateSameLogicalSubscription(){Subscription existing=new Subscription();when(subscriptions.findByExternalProviderAndExternalSubscriptionId("MERCADO_PAGO","pre-1")).thenReturn(Optional.of(existing));when(client.getPreapproval("pre-1")).thenReturn(preapproval("authorized"));processor.process("req-2","subscription_preapproval","pre-1");verify(subscriptions).save(existing);}
    @Test void canceledOnlyCancelsPaymentProvider(){Subscription paid=new Subscription();paid.setStatus(SubscriptionStatus.ACTIVE);when(subscriptions.findByExternalProviderAndExternalSubscriptionId("MERCADO_PAGO","pre-1")).thenReturn(Optional.of(paid));when(client.getPreapproval("pre-1")).thenReturn(preapproval("cancelled"));processor.process("req","subscription_preapproval","pre-1");assertThat(paid.getStatus()).isEqualTo(SubscriptionStatus.CANCELED);assertThat(checkout.getStatus()).isEqualTo(BillingCheckoutStatus.CANCELED);}
    @Test void authorizedPaymentIsResolvedToOfficialPreapproval(){when(client.getAuthorizedPayment("pay-1")).thenReturn(new MercadoPagoAuthorizedPayment("pay-1","rejected","pre-1"));when(client.getPreapproval("pre-1")).thenReturn(preapproval("authorized"));processor.process("req","subscription_authorized_payment","pay-1");verify(client).getPreapproval("pre-1");verify(subscriptions).save(any());}
    @Test void unknownOwnershipCreatesNothing(){when(client.getPreapproval("pre-x")).thenReturn(new MercadoPagoPreapproval("pre-x","authorized","unknown",null));when(checkouts.findByProviderSubscriptionId("pre-x")).thenReturn(Optional.empty());when(checkouts.findByExternalReference("unknown")).thenReturn(Optional.empty());assertThat(processor.process("req","subscription_preapproval","pre-x")).isEqualTo(MercadoPagoWebhookProcessor.Result.IGNORED);verifyNoInteractions(subscriptions);}
    @Test void pausedSuspendsExistingSubscription(){Subscription existing=existing(SubscriptionStatus.ACTIVE);when(client.getPreapproval("pre-1")).thenReturn(preapproval("paused"));when(subscriptions.findByExternalProviderAndExternalSubscriptionId("MERCADO_PAGO","pre-1")).thenReturn(Optional.of(existing));processor.process("req","subscription_preapproval","pre-1");assertThat(existing.getStatus()).isEqualTo(SubscriptionStatus.PAUSED);verify(subscriptions).save(existing);}
    @Test void pausedThenAuthorizedReturnsToActive(){Subscription existing=existing(SubscriptionStatus.PAUSED);when(client.getPreapproval("pre-1")).thenReturn(preapproval("authorized"));when(subscriptions.findByExternalProviderAndExternalSubscriptionId("MERCADO_PAGO","pre-1")).thenReturn(Optional.of(existing));processor.process("req","subscription_preapproval","pre-1");assertThat(existing.getStatus()).isEqualTo(SubscriptionStatus.ACTIVE);}
    @Test void pausedThenCanceledBecomesCanceled(){Subscription existing=existing(SubscriptionStatus.PAUSED);when(client.getPreapproval("pre-1")).thenReturn(preapproval("canceled"));when(subscriptions.findByExternalProviderAndExternalSubscriptionId("MERCADO_PAGO","pre-1")).thenReturn(Optional.of(existing));processor.process("req","subscription_preapproval","pre-1");assertThat(existing.getStatus()).isEqualTo(SubscriptionStatus.CANCELED);}
    @Test void waitingForGatewayKeepsActive(){assertPaymentState("waiting for gateway","rejected",SubscriptionStatus.ACTIVE,SubscriptionStatus.ACTIVE);}
    @Test void recyclingKeepsActive(){assertPaymentState("recycling","rejected",SubscriptionStatus.ACTIVE,SubscriptionStatus.ACTIVE);}
    @Test void individualRejectedRetryDoesNotBecomePastDue(){assertPaymentState("recycling","rejected",SubscriptionStatus.ACTIVE,SubscriptionStatus.ACTIVE);}
    @Test void definitivelyRejectedProcessedInvoiceBecomesPastDue(){assertPaymentState("processed","rejected",SubscriptionStatus.ACTIVE,SubscriptionStatus.PAST_DUE);}
    @Test void successfulInvoiceRecoversPastDueToActive(){assertPaymentState("processed","approved",SubscriptionStatus.PAST_DUE,SubscriptionStatus.ACTIVE);}
    @Test void canceledPreapprovalClosesPastDue(){Subscription existing=existing(SubscriptionStatus.PAST_DUE);when(client.getPreapproval("pre-1")).thenReturn(preapproval("canceled"));when(subscriptions.findByExternalProviderAndExternalSubscriptionId("MERCADO_PAGO","pre-1")).thenReturn(Optional.of(existing));processor.process("req","subscription_preapproval","pre-1");assertThat(existing.getStatus()).isEqualTo(SubscriptionStatus.CANCELED);}
    private MercadoPagoPreapproval preapproval(String status){return new MercadoPagoPreapproval("pre-1",status,"ref-1",null,Instant.parse("2026-08-01T00:00:00Z"),Instant.parse("2026-09-01T00:00:00Z"),Instant.parse("2026-08-28T00:00:00Z"));}
    private Subscription existing(SubscriptionStatus status){Subscription subscription=new Subscription();subscription.setStatus(status);return subscription;}
    private void assertPaymentState(String invoiceStatus,String paymentStatus,SubscriptionStatus initial,SubscriptionStatus expected){Subscription existing=existing(initial);when(subscriptions.findByExternalProviderAndExternalSubscriptionId("MERCADO_PAGO","pre-1")).thenReturn(Optional.of(existing));when(client.getAuthorizedPayment("pay-1")).thenReturn(new MercadoPagoAuthorizedPayment("pay-1",invoiceStatus,"pre-1",paymentStatus));when(client.getPreapproval("pre-1")).thenReturn(preapproval("authorized"));processor.process("req-"+invoiceStatus,"subscription_authorized_payment","pay-1");assertThat(existing.getStatus()).isEqualTo(expected);}
    private BillingCheckout checkout(){BillingCheckout c=new BillingCheckout();c.setId(10L);c.setUser(new User());c.setPlan(new Plan());c.setBillingCycle(BillingCycle.MONTHLY);c.setQuotedPrice(new BigDecimal("79.90"));c.setVehicleCount(12);c.setExternalReference("ref-1");c.setStatus(BillingCheckoutStatus.PROVIDER_PENDING);return c;}
}
