package com.localuz.service.storage;

import java.util.Optional;
import org.springframework.web.multipart.MultipartFile;

/**
 * Storage of user files (avatars, logos, damage photos, document attachments).
 *
 * <p>Callers only handle keys (see {@link StorageKeys}); paths, buckets and URLs stay inside the implementations.
 * Keys are always generated by the storage itself - never accepted from clients.
 */
public interface FileStorageService {
    /**
     * Validates the content by its real type and stores it under a new server-generated key.
     *
     * @return the new key.
     * @throws InvalidStoredFileException if empty, too large or of a type not allowed for the category.
     * @throws StorageUnavailableException if the storage cannot be written.
     */
    String store(StorageCategory category, byte[] content);

    /** Same as {@link #store(StorageCategory, byte[])}, rejecting oversized uploads before reading them. */
    String store(StorageCategory category, MultipartFile file);

    /** Whether the key is valid and its content is present in this storage. */
    boolean exists(String key);

    /** The stored content, or empty if the key is invalid or absent. */
    Optional<StoredFileContent> open(String key);

    /**
     * Removes a file previously created by this storage. Legacy (historical S3) keys are never deleted.
     *
     * @return true if a file was removed.
     */
    boolean delete(String key);

    /** Whether the storage is ready to be written. */
    boolean isAvailable();
}
