export const COLORS = [
  "Preto",
  "Branco",
  "Prata",
  "Vermelho",
  "Cinza",
  "Outros",
];

export const STATES_BR = [
  "AC",
  "AL",
  "AP",
  "AM",
  "BA",
  "CE",
  "DF",
  "ES",
  "GO",
  "MA",
  "MS",
  "MT",
  "MG",
  "PA",
  "PB",
  "PR",
  "PE",
  "PI",
  "RJ",
  "RN",
  "RS",
  "RO",
  "RR",
  "SC",
  "SP",
  "SE",
  "TO",
];

export const BODY_DAMAGES = [
  "Caixa-de-Ar Direita",
  "Caixa-de-Ar Esquerda",
  "Capô",
  "Parachoque Dianteiro",
  "Parachoque Traseiro",
  "Paralamas Traseiro Direita",
  "Paralamas Traseiro Esquerdo",
  "Paralamas Dianteiro Direita",
  "Paralamas Dianteiro Esquerdo",
  "Porta Dianteira Direita",
  "Porta Dianteira Esquerda",
  "Porta Traseira Direita",
  "Porta Traseira Esquerdo",
  "Tampa do Porta-Malas",
  "Teto",
  "Longarina",
  "Assoalho do Porta-Malas",
  "Parabrisa Dianteiro",
  "Parabrisa Traseiro",
  "Janela Porta Dianteira Direita",
  "Janela Porta Dianteira Esquerda",
  "Janela Porta Traseira Direita",
  "Janela Porta Traseira Esquerda",
  "Retrovisor Lateral Direito",
  "Retrovisor Lateral Esquerdo",
  "Farol Dianteiro Direito",
  "Farol Dianteiro Esquerdo",
  "Lanterna Traseira Direita",
  "Lanterna Traseira Esquerda",
  "Banco Motorista",
  "Banco Copiloto",
  "Bancos Traseiros",
  "Forro do Teto",
  "Forro do Assoalho",
];

export const EXPENSES = [
  "Aditivo Radiador",
  "Limpeza",
  "Óleo de Motor",
  "Lâmpadas",
  "Fluído de Freio",
  "Óleo de Direção",
  "Palhetas Parabrisa",
  "Presilhas de forro",
  "Lubrificante",
  "Massa de polir",
];

export const TIRE_BRANDS = [
  "CEAT",
  "IRA",
  "ITARO",
  "KENDA",
  "KOOGAR",
  "LEVORIN",
  "MAGGION",
  "METZELER",
  "MICHELIN",
  "PIRELLI",
  "RINALDI",
  "ROBUST",
  "SERVIS",
  "SPEEDMAX",
  "TAIGA",
  "VEE RUBBER",
  "WESTLAKE",
];

export const SERVICES = [
  "Abraçadeiras",
  "Adesivo Junta Do Motor",
  "Aditivo Radiador",
  "Alarme",
  "Alternador",
  "Amortecedor do Porta-malas",
  "Anel do Bujão",
  "Anel Dos Pitões",
  "Antena",
  "Ar Condicionado",
  "Armação Da Luz De Placa",
  "Articulador Axial",
  "Atuador Do Câmbio",
  "Auto-falante",
  "Balancim Do Motor",
  "Balança",
  "Bancos",
  "Bandeja - Direita",
  "Bandeja - Esquerda",
  "Base Da Coifa de Câmbio",
  "Batente",
  "Bateria",
  "Bomba de combustível",
  "Bomba de Água",
  "Bomba De Óleo",
  "Borracha Da Calha Do Teto",
  "Borracha Da Porta",
  "Borracha Do Porta-malas",
  "Borracha Do Pára-brisa",
  "Braçadeira",
  "Bronzina Biela",
  "Bronzina Mancal",
  "Bucha da Balança",
  "Bujão",
  "Buzinas",
  "Cabeçote do Motor ( Retífica)",
  "Cabo Da Embreagem",
  "Cabo De Aço Do Câmbio",
  "Cabos de Vela",
  "Calço Do Câmbio",
  "Calço do Motor",
  "Canister",
  "Capa Chave",
  "Capa Da Correia Dentada",
  "Capa de Banco",
  "Capa Do Retrovisor",
  "Caridade",
  "Carroceria/Chasis",
  "Catalisador",
  "Cebolinha Óleo",
  "Chave De Roda",
  "Chave de Seta",
  "Chave do Farol",
  "Chave Ignição",
  "Chave Segredo",
  "Cilindro Mestre",
  "Cilindro Roda Traseira",
  "Cinto",
  "Coifa",
  "Coifa da Caixa de Direção",
  "Coifa Da Homocinetica",
  "Coifa Da Suspensão",
  "Coifa Do Câmbio",
  "Coifa Homocinética",
  "Cola do Câmbio",
  "Comando De Válvula",
  "Conjunto De Junta Completo C/ Retentor",
  "Controle",
  "Correia ( Ar Condicionado )",
  "Correia - Alternador",
  "Correia Dentada",
  "Correias",
  "Coxim do Amortecedor",
  "Coxim Superior Do Câmbio",
  "Cubo Da Roda",
  "Cárter",
  "Descarbonizante",
  "Destravamento Das Pinças De Freio",
  "Difusor De Ar",
  "Direção Hidráulica",
  "Disco de Freio",
  "Elétrica",
  "Embreagem",
  "Estepe Novo",
  "Extensor Correia",
  "Fechadura Da Porta",
  "Filtro Ar Condicionado",
  "Filtro de Ar",
  "Filtro de Ar da Cabine",
  "Filtro de Combustível",
  "Filtro de Óleo",
  "Flange (bomba de combustível)",
  "Fluido da Embreagem",
  "Fluido da Transmissão",
  "Fluido de Freio",
  "Forro Da Porta",
  "Funilaria",
  "Fusível",
  "Garfo/Colar",
  "Graxa Da Trizeta",
  "Graxa do Câmbio",
  "Gás Do Ar Condicionado",
  "Homocinética",
  "Imobilizador",
  "Inspeção Técnica",
  "Interruptor De Freio",
  "Jogo De Junta Superior",
  "Junta Da Tampa De Válvula",
  "Junta do Cabeçote",
  "Junta Do Cárter",
  "Junta Homocinética",
  "Kit Amortecedor",
  "Kit barra estabilizadora Dianteira",
  "Kit Coifa Roda",
  "Kit Correia Dentada",
  "Kit Tensor Correia Do Comando",
  "Lanterna - Ré",
  "Lanterna de Freio",
  "Lanternagem",
  "Limitadores Porta",
  "Limpa Contato",
  "Limpadores de Para-brisa",
  "Limpeza",
  "Limpeza de Bicos",
  "Limpeza do Radiador",
  "Linha de Combustível",
  "Lubrificante",
  "Luz Farol Lado Esquerdo",
  "Luzes",
  "Lâmpadas",
  "Macaco Novo",
  "Mangueira Direção Hidráulica",
  "Mangueira Filtro de Ar",
  "Mangueira Radiador",
  "Mangueiras",
  "Manopla do Câmbio",
  "Massa De Calafetar",
  "Mão de obra",
  "Módulo do Abs",
  "Oleo Da Direção Hidráulica",
  "Oleo De Freio",
  "Palheta Parabrisa Dianteiros",
  "Palheta Parabrisa Traseiro",
  "Parafuso",
  "Pastilha de Freio",
  "Patins De Freio",
  "Patins Freio",
  "Película",
  "Pestana Da Porta",
  "Pino Do Pedal Da Embreagem",
  "Pivô",
  "Pivô Esquerdo",
  "Piça De Freio ( Parafusos)",
  "Pneus",
  "Pneus - Alinhamento/Balanceamento",
  "Pneus - Calibragem",
  "Pneus - Cambagem",
  "Pneus - Geometria",
  "Pneus - Montagem",
  "Pneus - Reparo",
  "Pneus - Rodízio",
  "Pneus - Válvula De Ar",
  "Polia Correia Do Alternador",
  "Polia Correia do Ar-Condicionado",
  "Polia Do Alternador",
  "Presilha De Forro Renault Clio",
  "Quebra-sol",
  "Querosene",
  "Radiador",
  "Rastreador",
  "Regulagem do Cabeçote",
  "Relé",
  "Remoção Parafuso Segredo",
  "Reparo - Ar Quente",
  "Reparo - Caixa De Direção",
  "Reparo - Câmbio",
  "Reparo - Escapamento",
  "Reparo - Mola do Banco",
  "Reparo - Radiador",
  "Reparo - Vidro",
  "Reparo Bomba Do Hidráulico",
  "Reparo Motor de Partida",
  "Reparo No Chicote",
  "Reparo no hidrovácuo",
  "Reparo no Motor",
  "Reservatório de Gasolina",
  "Reservatório De Água",
  "Retentor Da Polia",
  "Retentor De Válvula",
  "Retentor Do Comando",
  "Retentor Do Trembulador",
  "Retentor Do Virabrequim",
  "Retentor Lateral Câmbio",
  "Retirada Do Radiador",
  "Retrovisor",
  "Revisão",
  "Revisão freios",
  "Roda (parafusos)",
  "Rodas (desempeno)",
  "Rodas - Calotas",
  "Rolamentos",
  "Sapatas Freio Traseiro",
  "Scanner",
  "Semi Eixo",
  "Sensor De Detonação",
  "Sensor De Rotação",
  "Sensor De Temperatura",
  "Sensor De Velocidade",
  "Sensor Do Catalizador",
  "Serviço De Torneiro",
  "Silicone",
  "Sistema de Aquecimento",
  "Sistema de Embreagem",
  "Sistema de Exaustão",
  "Sistema de Refrigeramento",
  "Solda Na Balança",
  "Som",
  "Sonda Lambda",
  "Soquete Do Farol Dianteiro",
  "Suporte Braço Tensor Dianteiro",
  "Suspensão/Amortecedores",
  "Tambor De Freio",
  "Tampa do Radiador",
  "Tbi",
  "Tensor",
  "Terminal De Direção",
  "Trava Da Pastilha",
  "Trava Elétrica",
  "Trava Porta Direita",
  "Trava Porta-Malas",
  "Trizeta",
  "Troca Calço Do Motor",
  "Troca Correia Dentada",
  "Troca Coxim Do Amortecedor",
  "Troca Coxim Do Câmbio",
  "Troca Da Balança",
  "Troca Da Bucha Da Balança",
  "Troca da Coifa",
  "Troca Da Coifa Do Câmbio",
  "Troca da Embreagem",
  "Troca Da Rotunga Da Culatra",
  "Troca Da Sapata De Freio",
  "Troca Da Válvula Termostática",
  "Troca Das Velas",
  "Troca de Freio",
  "Troca de Óleo",
  "Troca De Óleo + Filtro Óleo/ Ar / Combustível",
  "Troca Do Amortecedor",
  "Troca Do Braço Axial",
  "Troca Do Miolo Da Chave",
  "Troca Do Pivô",
  "Troca Do Prisioneiro",
  "Troca do Rolamento",
  "Troca do Terminal De Direção",
  "Troca Pastilhas",
  "Troca Retentor Do Câmbio",
  "Troca Óleo Do Câmbio",
  "Tucho Do Motor",
  "Tulipa Câmbio",
  "Velas de Ignição",
  "Vidros/Espelhos",
  "Válvula De Escape",
  "Válvula Termostatica",
  "Óleo de Motor",
  "Óleo Caixa De Direção",
  "Óleo Do Câmbio",
];

export const CLEANING = ["Péssima", "Ruim", "Aceitavel", "Boa", "Ótima"];

export const INTEGRITY = [
  "0-10%",
  "10-20%",
  "30-50%",
  "50-70%",
  "70-90%",
  "90-100%",
];

export enum REPORTS {
  month = "Do Mês",
  history = "Histórico Financeiro",
  maintenance = "Manutenções"
}

export const INCOMES = [
  "Aluguel",
  "Aluguel com desconto",
  "Manutenção compartilhada",
];

export const DRIVER_PENDENCIES = [
  "Aluguel atrasado",
  "Dano",
  "Dívida",
  "Multa",
  "Manutenção compartilhada",
];
