export const TEXT = {
  appTitle: "Frotto",
  login: "Login",
  register: "Cadastro",
  doRegister: "Fazer o Cadastro",
  registerAction: "Cadastrar",
  firstName: "Nome",
  email: "E-mail",
  password: "Senha",
  invalidEmail: "E-mail inválido",
  invalidCPF: "CPF inválido",
  requiredField: "Preencha este campo",
  search: "Pesquisar",
  searchAdd: "Pesquisar ou Adicionar",
  minFieldSize: (value: string) => "Mínimo " + value + " caracteres",
  maxFieldSize: (value: string) => "Máximo " + value + " caracteres",
  minFieldNumber: (value: string) => "Mínimo " + value,
  maxFieldNumber: (value: string) => "Máximo " + value,
  registerFailed: "Não foi possível cadastrar. E-mail já existe",
  loginFailed: "Não foi possível autenticar.",
  loadCarsFailed: "Não foi possível carregar a lista de carros.",
  loadCarGroupsFailed: "Não foi possível carregar a lista de Grupos.",
  loadCarDamagesFailed: "Não foi possível carregar a lista de danos do carro.",
  loadDriversFailed: "Não foi possível carregar a lista de motoristas.",
  loadInspectionsFailed: "Não foi possível carregar a lista de inspeções.",
  loadIncomesFailed: "Não foi possível carregar a lista de receitas.",
  loadPendenciesFailed:
    "Não foi possível carregar a lista de pendencias do motorista.",
  loadRemindersFailed: "Não foi possível carregar a lista de lembretes.",
  loadCarExpensesFailed: "Não foi possível carregar a lista de despesas.",
  loadMaintenancesFailed: "Não foi possível carregar a lista de manutenções.",
  loadCarFailed: "Não foi possível carregar os dados do carro.",
  saveFailed: "Erro ao tentar salvar",
  deleteFailed: "Erro ao tentar excluir",
  activeDriverExist: "Já existe outro motorista ativo neste carro",
  itensNotFound: "Nenhum item encontrado",
  edit: "Editar",
  select: "Selecione",
  addItem: "Adicionar",
  damage: "Danos",
  cars: "Carros",
  car: "Carro",
  carInfo: "Dados do Carro",
  reports: "Relatórios",
  report: "Relatório",
  generateReport: "Gerar Relatório",
  carDamages: "Danos no Carro",
  carDamagesActive: "Ativo",
  carDamagesDone: "Anteriores",
  active: "Ativo",
  km: "Km",
  addCar: "Carro",
  addCarDamage: "Dano",
  addCarDriver: "Motorista",
  addCarInspection: "Inspeção",
  addCarMaintenance: "Manutenção",
  new: "Novo",
  newIncome: "Nova",
  newCarExpense: "Nova",
  newInspection: "Nova Inspeção",
  all: "Ver todos",
  cancel: "Cancelar",
  delete: "Excluir",
  deleteDefault: "Gostaria de Excluir ",
  confirm: "Confirmar",
  save: "Salvar",
  carModel: "Marca - Modelo",
  color: "Cor",
  plate: "Placa",
  odometer: "Odômetro",
  administrationFee: "Taxa de Gestão em %",
  commissionType: "Tipo de comissao",
  commissionPercent: "Comissao % do lucro",
  commissionFixed: "Comissao fixa (R$)",
  commissionChargeOnLoss: "Cobrar comissao fixa com lucro negativo",
  initialValue: "Valor Inicial",
  group: "Dono/Grupo",
  year: "Ano",
  date: "Data",
  dateStart: "Data de Início",
  dateEnd: "Data de Fim",
  carData: "Carro",
  driver: "Motorista",
  lastInspection: "Última Inspeção",
  lastMaintenance: "Última manutenção",
  driverContract: "Contrato do Motorista",
  drivers: "Motoristas",
  inspections: "Inspeções",
  inspection: "Inspeção",
  reminders: "Lembretes",
  reminder: "Lembrete",
  incomes: "Receitas",
  income: "Receita",
  incomeName: "Nome da Receita",
  carExpenses: "Despesas",
  carExpense: "Despesa",
  carExpenseName: "Nome da Despesa",
  maintenances: "Manutenções",
  maintenance: "Manutenção",
  driverPendencies: "Pendências",
  driverPendency: "Pendência",
  inspectionsExpenses: "Despesas",
  maintenanceServices: "Serviços",
  add: "Adicionar",
  expense: "Despesa",
  replicateExpense: "Replicar esta despesa em todos os carros",
  serviço: "Serviço",
  expenseLabe: "Tipo da Despesa",
  cleaning: "Limpeza",
  intern: "Interna",
  extern: "Externa",
  tires: "Pneus",
  tire: "Pneu",
  leftFront: "Dianteiro Esquerdo",
  rightFront: "Dianteiro Direito",
  leftFBack: "Traseiro Esquerdo",
  rightFBack: "Traseiro Direito",
  // leftFrontSymbol: "Fr Es",
  // rightFrontSymbol: "Fr Di",
  // leftFBackSymbol: "Tr Es",
  // rightFBackSymbol: "Tr Di",
  spare: "Estepe",
  model: "Modelo",
  service: "Serviço",
  services: "Serviços",
  product: "Produto",
  integrity: "Integridade",
  noDriver: "Nenhum motorista ativo",
  noInspection: "Nenhuma inspeção feita",
  noMaintenance: "Nenhuma Manutenção feita",
  noExpenses: "Nenhuma despesa adicionada",
  noServices: "Nenhum serviço adicionado",
  noReminders: "Nenhum lembrete",
  noCarBodyDamages: "Nenhum dano na lataria adicionado",
  local: "Local",
  cpf: "CPF",
  name: "Nome",
  contact: "Contato",
  emergencyContact: "Contato de Emergência",
  documentLicense: "CNH",
  documentRegister: "RG",
  publicScore: "Score público",
  country: "País",
  state: "Estado",
  city: "Cidade",
  district: "Bairro",
  address: "Endereço",
  warranty: "Caução",
  score: "Nota",
  debt: "Dívida",
  zip: "Cep",
  part: "Peça",
  cost: "Custo",
  value: "Valor",
  totalCost: "Custo Total",
  total: "Total",
  ammount: "Quantidade",
  responsible: "Responsavel",
  resolved: "Finalizado",
  notResolved: "Pendente",
  photo: "Foto",
  photo2: "Foto 2",
  gallery: "Selecionar do Álbum",
  takePicture: "Tirar Foto",
  moneySymbol: "R$",
  zeroMoney: "R$ 0,00",
  logout: "Logout",
  theme: "Tema",
  themeDark: "Tema escuro",
  themeLight: "Tema claro",
};
